### ISSUE TITLE
Error: Nonce has already been used for this request

### ISSUE THREAD

**Issue by volkerhehl** [mjezorek/cryptopia-node#3]
Has anyone else this problem too?
This error occurs randomly, eg. 1 time per 20 requests.

```
undefined:1
{"Success":false,"Error":"Nonce has already been used for this request."}
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/volker/Repos/coin-o-matic/node_modules/cryptopia-node/index.js:197:31)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by volkerhehl** [comment]
Ok, seem to be two errors. The other ist that the error response from the Cryptopia API are invalid JSON. But i can't see why?! ...

**Comment by volkerhehl** [comment]
See pull request ... to remove nonce granulation to 1 second works for me

**Comment by mjezorek** [comment]
Resolved by pull
